/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainReviewRouteImport } from './routes/_main/review'
import { Route as MainAnalysisIndexRouteImport } from './routes/_main/analysis/index'
import { Route as MainAddIndexRouteImport } from './routes/_main/add/index'
import { Route as MainExpensesIdRouteImport } from './routes/_main/expenses/$id'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/setup/',
  path: '/setup/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainReviewRoute = MainReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAnalysisIndexRoute = MainAnalysisIndexRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAddIndexRoute = MainAddIndexRouteImport.update({
  id: '/add/',
  path: '/add/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainExpensesIdRoute = MainExpensesIdRouteImport.update({
  id: '/expenses/$id',
  path: '/expenses/$id',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/review': typeof MainReviewRoute
  '/settings': typeof MainSettingsRoute
  '/': typeof MainIndexRoute
  '/setup': typeof SetupIndexRoute
  '/expenses/$id': typeof MainExpensesIdRoute
  '/add': typeof MainAddIndexRoute
  '/analysis': typeof MainAnalysisIndexRoute
}
export interface FileRoutesByTo {
  '/review': typeof MainReviewRoute
  '/settings': typeof MainSettingsRoute
  '/': typeof MainIndexRoute
  '/setup': typeof SetupIndexRoute
  '/expenses/$id': typeof MainExpensesIdRoute
  '/add': typeof MainAddIndexRoute
  '/analysis': typeof MainAnalysisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteRouteWithChildren
  '/_main/review': typeof MainReviewRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/': typeof MainIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/_main/expenses/$id': typeof MainExpensesIdRoute
  '/_main/add/': typeof MainAddIndexRoute
  '/_main/analysis/': typeof MainAnalysisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/review' | '/settings' | '/' | '/setup' | '/expenses/$id' | '/add' | '/analysis'
  fileRoutesByTo: FileRoutesByTo
  to: '/review' | '/settings' | '/' | '/setup' | '/expenses/$id' | '/add' | '/analysis'
  id: '__root__' | '/_main' | '/_main/review' | '/_main/settings' | '/_main/' | '/setup/' | '/_main/expenses/$id' | '/_main/add/' | '/_main/analysis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren
  SetupIndexRoute: typeof SetupIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/review': {
      id: '/_main/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof MainReviewRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/analysis/': {
      id: '/_main/analysis/'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof MainAnalysisIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/add/': {
      id: '/_main/add/'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof MainAddIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/expenses/$id': {
      id: '/_main/expenses/$id'
      path: '/expenses/$id'
      fullPath: '/expenses/$id'
      preLoaderRoute: typeof MainExpensesIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface MainRouteRouteChildren {
  MainReviewRoute: typeof MainReviewRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainExpensesIdRoute: typeof MainExpensesIdRoute
  MainAddIndexRoute: typeof MainAddIndexRoute
  MainAnalysisIndexRoute: typeof MainAnalysisIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainReviewRoute: MainReviewRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainIndexRoute: MainIndexRoute,
  MainExpensesIdRoute: MainExpensesIdRoute,
  MainAddIndexRoute: MainAddIndexRoute,
  MainAnalysisIndexRoute: MainAnalysisIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(MainRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  SetupIndexRoute: SetupIndexRoute,
}
export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
